# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-03 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_explorer', '0003_auto_20171002_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
