# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-03 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_explorer', '0004_auto_20171003_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(default=b'bbc-news', max_length=20),
        ),
    ]
